import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationWrapper } from "../components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adyt Studios",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/platform_images/adyt_logo.svg',
        type: 'image/svg+xml',
      },
    ],
    shortcut: '/platform_images/adyt_logo.svg',
    apple: '/platform_images/adyt_logo.svg',
  },
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/platform_images/adyt_logo.svg" />
        <link rel="apple-touch-icon" href="/platform_images/adyt_logo.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <NavigationWrapper />
        {children}
      </body>
    </html>
  );
}
